# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages

services:
  - docker  

matrix:
  include:
    - before_script:
        - cd TrafficSignalsConfigurator
      script:
          - bash ../build-and-push-image-to-docker-hub.sh $TRAVIS_BUILD_NUMBER trafficsignalconfigurator $DOCKER_HUB_USER $DOCKER_HUB_PASSWORD $TRAVIS_BRANCH

    - before_script:
        - cd EventsStore
      script:
          - bash ../build-and-push-image-to-docker-hub.sh $TRAVIS_BUILD_NUMBER eventstore $DOCKER_HUB_USER $DOCKER_HUB_PASSWORD $TRAVIS_BRANCH


notifications:
  email:
    - gigapr@hotmail.com