#!/bin/bash

export BUILD_NUMBER=$1
export REPOSITORY_NAME=$2
export DOCKER_HUB_USER=$3
export DOCKER_HUB_PASSWORD=$4

export IMAGE_NAME=$REPOSITORY_NAME:$BUILD_NUMBER

docker build -t $IMAGE_NAME .
docker tag $IMAGE_NAME $DOCKER_HUB_USER/$IMAGE_NAME
docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
docker push $DOCKER_HUB_USER/$IMAGE_NAME