apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trafficsignals-configurator
  namespace: threeamigos
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gigapr/doggystuff:91
        name: trafficsignals-configurator
        resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
        ports:
          - containerPort: 5050


---
apiVersion: v1
kind: Service
metadata:
  name: trafficsignals-configurator
  namespace: namespace
spec:
  type: NodePort
  ports:
    - nodePort: 5050
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: trafficsignals-configurator