apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trafficsignals-configurator
  namespace: threeamigos
spec:
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: threeamigos/trafficsignalconfigurator:150
        name: trafficsignals-configurator
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5001


---
apiVersion: v1
kind: Service
metadata:
  name: trafficsignals-configurator
  namespace: threeamigos
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: trafficsignals-configurator