apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trafficsignals-configurator
  namespace: threeamigos
  labels:
    name: trafficsignals-configurator
spec:
  template:
    metadata:
      labels:
        app: trafficsignals-configurator
    spec:
      containers:
      - image: threeamigos/trafficsignalconfigurator:153
        name: trafficsignals-configurator
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: trafficsignals-configurator
  namespace: threeamigos
spec:
  type: NodePort
  ports:
    - nodePort: 31993
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: trafficsignals-configurator